idp:
  appId: appid
  entityId: entityid
  postLogoutURL: /
  metadataURL: http://idp.ssocircle.com/idp-meta.xml

server:
  port: 8443
  ssl:
    key-alias: spring
    key-store: classpath:keystore.jks
    key-store-password: secret